---
title: "HW4"
author: "Faiz Ikramulla"
date: "December 5, 2018"
output:
  html_document:
    code_folding: hide
#runtime: shiny
---

```{r echo=T, warning= FALSE, message= FALSE}
library(openxlsx)
#library(shiny)
library(plotly)
library(dplyr)
library(tidyr)
#load the rvest package

library(rvest)
library(XML)
library(xml2)
# General-purpose data wrangling
library(tidyverse)  
# Parsing of HTML/XML files  
library(rvest)    
# String manipulation
library(stringr)   
# Verbose regular expressions
library(rebus)     
# Eases DateTime manipulation
library(lubridate)

#MOVIE ACTORS - specify website to be scraped

url = "https://www.imdb.com/title/tt1201607/fullcredits?ref_=tt_ql_1"

page = read_html(url)

movie.nodes <- html_nodes(page,'table')
htmltable <- html_table(movie.nodes)

df <- data.frame(htmltable[3])

df2 <- data.frame(df$X2,df$X4)

colnames(df2) <- c("ACTOR","CHARACTER")

#df2 <- df2[-which(df$ACTOR == ""), ] #try
#df2 <- na.omit(df2)  #try

df3 <- separate(df2, ACTOR, c("First Name", "Last Name"), sep = " ")

head(df3,10)

#BASKETBALL - specify website to be scraped

url = "http://www.espn.com/nba/team/stats/_/name/sa/san-antonio-spurs"

page = read_html(url)

stats.nodes <- html_nodes(page,'table')
htmltable <- html_table(stats.nodes)
df <- data.frame(htmltable[2])
#colnames(df)

df2 <- data.frame(df$X1,df$X4)

colnames(df2) <- c("PLAYER","FGP")

df2 <- df2[-c(1, 2), ]
df2
sapply(df2, class) 
df2$FGP <- as.numeric(as.character(df2$FGP))
#df2$PLAYER <- as.numeric(as.character(df2$PLAYER))
sapply(df2, class)


df3 <- df2[order(df2$FGP),]

row.names(df3) <- 1:nrow(df3)

df3 <- df3[-c(8), ]
row.names(df3) <- 1:nrow(df3)
df3
df3$PLAYER

#df3$PLAYERs <-factor(df3$PLAYER, levels = c("jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec")
#df3$PLAYER <- factor(df3$PLAYER, levels = c(1,2,3,4,5,6,7,8,9,,10,11,12,13,14))


p <-ggplot(df3, aes(PLAYER, FGP))
p +geom_bar(stat = "identity")







